# Generated by Django 3.2.7 on 2021-11-19 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
