# Generated by Django 3.2.7 on 2021-12-18 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_admins_name_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
