# Generated by Django 3.2.7 on 2021-12-14 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blog',
        ),
    ]
