# Generated by Django 3.2.7 on 2021-12-14 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blog',
        ),
    ]
