# Generated by Django 3.2.7 on 2021-12-14 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog',
            new_name='blogg',
        ),
    ]
