# Generated by Django 3.2.7 on 2022-02-22 11:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_blog_blogg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogg',
            name='text_blog',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
